import type { Metadata } from "next";
import "./globals.css";
// @ts-ignore
import Navbar from "@/Components/NavBar";
import Footer from "@/Components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-screen antialiased">
      <body className="min-h-screen flex flex-col __bm__extension">
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
