import Image from "next/image";
import Header from "@/Components/Header";
import Galleri from "@/Components/GalleriForeside";
import ArtistCards from "@/Components/ArtistCards";
import HistorikGal from "@/Components/HistorikGal";
import KulturCards from "@/Components/KulturCards";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="w-full flex-1 bg-brown text-white">
      <Header />
      <Galleri />
      <ArtistCards />
      <HistorikGal />
      
      <KulturCards />
    </main>
  );
}